begin;

drop table if exists order_items cascade;
drop table if exists meals cascade;
drop table if exists orders cascade;
drop table if exists shops cascade;
drop table if exists restaurants cascade;
drop table if exists users cascade;

create table if not exists users (
  id integer generated by default as identity primary key,
  username varchar(100) not null,
  first_name varchar(100) not null default 'Jakab',
  last_name varchar(100) not null default 'Gipsz',
  email varchar(100) not null,
  password_hash text not null,
  address varchar(150) not null default 'Szeged, Roosevelt tér 1.',
  role varchar(20) not null default 'user',

  constraint users_username_unique unique (username),
  constraint users_email_unique unique (email),
  constraint users_role_check check (role in ('user', 'owner', 'admin', 'courier', 'customer')),
  constraint users_username_length_check check (char_length(username) >= 3),
  constraint users_first_name_length_check check (char_length("first_name") >= 1),
  constraint users_last_name_length_check check (char_length("last_name") >= 1),
  constraint users_email_format_check check (position('@' in email) > 1),
  constraint users_address_length_check check (char_length(address) >= 5),
  constraint users_password_hash_length_check check (char_length(password_hash) >= 20)
);

create table if not exists restaurants (
  id integer generated by default as identity primary key,
  name varchar(100) not null default 'Royal Bistro',
  owner_id integer not null,

  constraint restaurants_owner_id_fkey
    foreign key (owner_id)
    references users(id)
    on delete restrict
    on update cascade,

  constraint restaurants_name_length_check check (char_length(name) >= 2),
  constraint restaurants_name_owner_unique unique (name, owner_id)
);

create table if not exists shops (
  id integer generated by default as identity primary key,
  name varchar(100) not null default 'Royal Shop',
  owner_id integer not null,

  constraint shops_owner_id_fkey
    foreign key (owner_id)
    references users(id)
    on delete restrict
    on update cascade,

  constraint shops_name_length_check check (char_length(name) >= 2),
  constraint shops_name_owner_unique unique (name, owner_id)
);

create table if not exists meals (
  id integer generated by default as identity primary key,
  name varchar(100) not null default 'Napi menü',
  description varchar(255) not null default 'Frissen készített, ízletes fogás',
  price integer not null default 1000,
  restaurant_id integer not null,

  constraint meals_restaurant_id_fkey
    foreign key (restaurant_id)
    references restaurants(id)
    on delete restrict
    on update cascade,

  constraint meals_name_length_check check (char_length(name) >= 2),
  constraint meals_description_length_check check (char_length(description) >= 3),
  constraint meals_price_check check (price >= 0),
  constraint meals_name_restaurant_unique unique (name, restaurant_id),
  constraint meals_id_restaurant_unique unique (id, restaurant_id)
);

create table if not exists orders (
  id integer generated by default as identity primary key,
  restaurant_id integer not null,
  user_id integer not null,
  ordered_at timestamp with time zone not null default now(),

  constraint orders_restaurant_id_fkey
    foreign key (restaurant_id)
    references restaurants(id)
    on delete restrict
    on update cascade,

    constraint orders_user_id_fkey
    foreign key (user_id)
    references users(id)
    on delete restrict
    on update cascade,

  constraint orders_id_restaurant_unique unique (id, restaurant_id)
);

create table if not exists order_items (
  id integer generated by default as identity primary key,
  order_id integer not null,
  meal_id integer not null,
  restaurant_id integer not null,
  quantity integer not null default 1,
  unit_price integer not null,

  constraint order_items_order_id_fkey
    foreign key (order_id)
    references orders(id)
    on delete cascade
    on update cascade,

  constraint order_items_meal_id_fkey
    foreign key (meal_id)
    references meals(id)
    on delete restrict
    on update cascade,

  constraint order_items_order_restaurant_fkey
    foreign key (order_id, restaurant_id)
    references orders(id, restaurant_id)
    on delete cascade
    on update cascade,

  constraint order_items_meal_restaurant_fkey
    foreign key (meal_id, restaurant_id)
    references meals(id, restaurant_id)
    on delete restrict
    on update cascade,

  constraint order_items_quantity_check check (quantity > 0),
  constraint order_items_unit_price_check check (unit_price >= 0),
  constraint order_items_order_meal_unique unique (order_id, meal_id)
);

insert into users (id, username, first_name, last_name, email, password_hash, address, role) values
(1, 'Nagypeter', 'Péter', 'Nagy', 'nagypeter@gmail.com', '$2a$10$JOErmXxb0i5C9fECsUkvuuiFIEs/xE8K92z3cLjXVsKuC5E4RFsdm', 'Budapest, Szökőkút utca 10.', 'owner'),
(2, 'Kovacsanna', 'Anna', 'Kovács', 'akicsi@freemail.hu', '$2a$10$JOErmXxb0i5C9fECsUkvuubDlh4Hiwr9RwC8Gbu9cBJHJxMdjElBW', 'Szeged, Bálint Sándor utca 5.', 'owner'),
(3, 'Nagygabor', 'Gábor', 'Nagy', 'nagy.gabor@freemail.hu', '$2a$10$JOErmXxb0i5C9fECsUkvuuUA2q8EGmY7aPeh4py683GIjfG.HpjSy', 'Debrecen, Kossuth Lajos utca 15.', 'owner'),
(4, 'Totheszter', 'Eszter', 'Tóth', 'eszter.toth@freemail.hu', '$2a$10$JOErmXxb0i5C9fECsUkvuuNUgY/6P08FzAoUp9C8LvGgXVfijcGEy', 'Miskolc, József Attila utca 20.', 'customer'),
(5, 'Szabolaszlo', 'László', 'Szabó', 'laszlo.szabo@freemail.hu', '$2a$11$E.QB16J01iyysd0rsSAiAejSCoowVtF5E1SHxptuIVUYid6IlsZtC', 'Pécs, Petőfi Sándor utca 8.', 'customer'),
(6, 'Kisszoltan', 'Zoltán', 'Kiss', 'egyszelvedojavito@citromail.hu', '$2a$12$3s72VLMwnslH0ZFDwtcze.ovrhFMVvtSzV364zycaAdQHbAjV3Y.2', 'Győr, Mária utca 12.', 'customer'),
(7, 'Magyarpeter', 'Péter', 'Magyar', 'mp@tisza.hu', '$scrypt$ln=14,r=8,p=1$6CldEWfdaLU9jnoLBE8dzw==$I0+jYzZEGql9fVzYvwqj0vB7cJIyMuSB8/XxhqtevfM=', 'Máriapócs, Vámospércs utca 91.', 'customer'),
(8, 'vidiorban', 'Vidi', 'Orbán', 'vidiorban@gmail.com', '$scrypt$ln=14,r=8,p=1$iNJbalI1HcEt9M32AP9Skg==$biOCmsWnDzWlot88p2MOutQEZo72nucjDQJldcWuCEA=', 'Budapest, Puskás Aréna 1.', 'customer'),
(9, 'jdoe', 'John', 'Doe', 'jdoe@email.com', '$argon2id$v=19$m=19456,t=2,p=1$cU9VMTI4QTZQNFFwTTBNU2YxRVViQT09$bmPkJ3Ft7MY/RyXBQdApSQYfaXOpP5y7ua18', '123 Main Street', 'customer'),
(10, 'asmith', 'Anna', 'Smith', 'asmith@email.com', '$argon2id$v=19$m=19456,t=2,p=1$cU9VMTI4QTZQNFFwTTBNU2YxRVViQT09$bmPkJ3Ft7MY/RyXBQdApSQYfaXOpP5y7ua18Pc55fa4', '45 King Road', 'customer'),
(11, 'bkovacs', 'Béla', 'Kovács', 'bkovacs@email.com', '$argon2id$v=19$m=19456,t=2,p=1$cU9VMTI4QTZQNFFwTTBNU2YxRVViQT09$56c95xEX//0I/xl2KfDJ3Sv3dZpgbHWNYTBjMtWE01c', '12 Petőfi utca', 'customer'),
(12, 'nagy.eva', 'Éva', 'Nagy', 'eva.nagy@email.com', '$argon2id$v=19$m=19456,t=2,p=1$cU9VMTI4QTZQNFFwTTBNU2YxRVViQT09$VhSV34sEkiIpI9R1T1ExrLBCvsxiUjeSZYTFXvk76yk', '78 Kossuth tér', 'customer'),
(13, 'tpeter', 'Péter', 'Tóth', 'tpeter@email.com', '$argon2id$v=19$m=19456,t=2,p=1$cU9VMTI4QTZQNFFwTTBNU2YxRVViQT09$wVRehf0aPdJRgnqpEkzCgVuaZeZX1WmxGD298UCUahU', '9 Rákóczi út', 'customer'),
(14, 'kzsuzsa', 'Zsuzsa', 'Kiss', 'kzsuzsa@email.com', '$argon2id$v=19$m=19456,t=2,p=1$cU9VMTI4QTZQNFFwTTBNU2YxRVViQT09$5d4eyAx0pz15SF7xZpxvdOXNLjGhF/2SyoYdyoMxepc', '33 Ady Endre utca', 'customer'),
(15, 'fmark', 'Márk', 'Farkas', 'fmark@email.com', '$argon2id$v=19$m=19456,t=2,p=1$cU9VMTI4QTZQNFFwTTBNU2YxRVViQT09$k8OFPlRGFxWqc83orc6OgKd/a/5p9MWj2qNy+gJydzE', '5 Béke tér', 'customer'),
(16, 'ghorvath', 'Gábor', 'Horváth', 'ghorvath@email.com', '$argon2id$v=19$m=19456,t=2,p=1$cU9VMTI4QTZQNFFwTTBNU2YxRVViQT09$fXvAoMgx+WOM0kBT7BZ40/sgUQdZuaGvPNzhLrF81Tg', '101 Duna sor', 'courier'),
(17, 'lbalazs', 'Balázs', 'Lakatos', 'lbalazs@email.com', '$argon2id$v=19$m=19456,t=2,p=1$cU9VMTI4QTZQNFFwTTBNU2YxRVViQT09$Q9KGArtDPiXVz7xowbRCp1HcouTYG8ta9InWvktjgyk', '67 Arany János utca', 'courier'),
(18, 'mrita', 'Rita', 'Molnár', 'mrita@email.com', '$argon2id$v=19$m=19456,t=2,p=1$cU9VMTI4QTZQNFFwTTBNU2YxRVViQT09$UIWXH/IoJ4DfmPot0cq5ln+iB4FDN+JKVO9XdTfiEwM', '22 Széchenyi utca', 'admin');

insert into restaurants (id, name, owner_id) values
(1, 'McDonald''s', 1),
(2, 'KFC', 2),
(3, 'Burger King', 3),
(4, 'Taj Mahal', 3),
(5, 'Buddha Original', 1),
(6, 'Király Bisztró', 1),
(7, 'Pizza Mester', 2),
(8, 'Sushi Szamuráj', 3),
(9, 'Pizzéria', 3),
(10, 'Royal Diner', 1),
(11, 'Palace Pizzeria', 2),
(12, 'Sovereign Sushi', 3),
(13, 'Vasvári Villás', 1),
(14, 'Vasvári Villás Reggeliző', 1);

insert into shops (id, name, owner_id) values
(1, 'Royal Alapanyagbolt', 1),
(2, 'Burger Kellék Shop', 2),
(3, 'Sushi Supply Store', 3),
(4, 'Vasvári Mini Market', 1);

insert into meals (id, name, description, price, restaurant_id) values
(1, 'Margherita Pizza', 'Friss paradicsom, mozzarella és bazsalikom', 1500, 1),
(2, 'Caesar Saláta', 'Ropogós saláta csirkével és krutonnal', 1200, 2),
(3, 'Spaghetti Carbonara', 'Klasszikus olasz tészta szalonnával és tojással', 1300, 3),
(4, 'Pepperoni Pizza', 'Szaftos pepperoni és olvadt sajt', 1600, 4),
(5, 'Hawaii Pizza', 'Ananász és sonka egy különleges kombinációban', 1700, 5),
(6, 'Vegetáriánus Pizza', 'Friss zöldségek és sajt egy egészséges választás', 1400, 6),
(7, 'California Roll', 'Rák, avokádó és uborka egy finom tekercsben', 2000, 7),
(8, 'Spicy Tuna Roll', 'Fűszeres tonhal és avokádó egy ízletes kombinációban', 2200, 8),
(9, 'Salmon Nigiri', 'Friss lazac egy szelet rizs tetején', 1800, 1),
(10, 'Gyros tál', 'Fűszeres csirkehús, sült burgonya, friss saláta és tzatziki', 1500, 1),
(11, 'Hamburger', 'Marhahúspogácsa, cheddar sajt, saláta, paradicsom és burger szósz', 1800, 1),
(12, 'Sült csirke', 'Ropogós bundában sült csirkemell hasábburgonyával', 2200, 1),
(13, 'Rántott sajt', 'Aranybarnára sütött sajt tartármártással és rizzsel', 1700, 1),
(14, 'Lazac steak', 'Grillezett lazac friss salátával és citromos öntettel', 3000, 1),
(15, 'Vegetáriánus lasagne', 'Rétegezett tészta zöldségekkel, paradicsomszósszal és sajttal', 2500, 4),
(16, 'Sült zöldségek', 'Kemencében sült idényzöldségek fokhagymás fűszerezéssel', 1200, 6),
(17, 'Sült krumpli', 'Frissen sült, ropogós hasábburgonya enyhén sózva', 500, 7),
(18, 'Kóla', 'Jéghideg szénsavas üdítőital 0,5 literes kiszerelésben', 1000, 8);

insert into orders (id, restaurant_id, user_id, ordered_at) values
(1, 1, 4, '2024-06-01'),
(2, 2, 5, '2024-06-02'),
(3, 3, 6, '2024-06-03'),
(4, 4, 7, '2024-06-04'),
(5, 5, 8, '2024-06-05'),
(6, 6, 9, '2024-06-06'),
(7, 7, 10, '2024-06-07'),
(8, 8, 11, '2024-06-08'),
(9, 9, 12, '2024-06-09'),
(10, 10, 13, '2024-06-10'),
(11, 11, 14, '2025-12-27'),
(12, 12, 15, '2026-01-31');

insert into order_items (id, order_id, meal_id, restaurant_id, quantity, unit_price) values
(1, 1, 1, 1, 2, 1500),
(2, 1, 9, 1, 1, 1800),
(3, 2, 2, 2, 1, 1200),
(4, 3, 3, 3, 2, 1300),
(5, 4, 4, 4, 1, 1600),
(6, 5, 5, 5, 1, 1700),
(7, 6, 6, 6, 2, 1400),
(8, 7, 7, 7, 3, 2000),
(9, 8, 8, 8, 1, 2200),
(10, 9, 15, 9, 1, 2500),
(11, 10, 10, 10, 2, 1500),
(12, 10, 11, 10, 1, 1800),
(13, 11, 17, 11, 2, 500),
(14, 12, 18, 12, 3, 1000);

create index if not exists restaurants_owner_id_idx on restaurants (owner_id);
create index if not exists shops_owner_id_idx on shops (owner_id);
create index if not exists meals_restaurant_id_idx on meals (restaurant_id);
create index if not exists orders_user_id_idx on orders (user_id);
create index if not exists orders_restaurant_id_idx on orders (restaurant_id);
create index if not exists order_items_order_id_idx on order_items (order_id);
create index if not exists order_items_meal_id_idx on order_items (meal_id);

select setval(pg_get_serial_sequence('users', 'id'), coalesce((select max(id) from users), 1), true);
select setval(pg_get_serial_sequence('restaurants', 'id'), coalesce((select max(id) from restaurants), 1), true);
select setval(pg_get_serial_sequence('shops', 'id'), coalesce((select max(id) from shops), 1), true);
select setval(pg_get_serial_sequence('meals', 'id'), coalesce((select max(id) from meals), 1), true);
select setval(pg_get_serial_sequence('orders', 'id'), coalesce((select max(id) from orders), 1), true);
select setval(pg_get_serial_sequence('order_items', 'id'), coalesce((select max(id) from order_items), 1), true);

commit;