/* eslint-disable */
import * as Router from 'expo-router';

export * from 'expo-router';

declare module 'expo-router' {
  export namespace ExpoRouter {
    export interface __routes<T extends string | object = string> {
      hrefInputParams: { pathname: Router.RelativePathString, params?: Router.UnknownInputParams } | { pathname: Router.ExternalPathString, params?: Router.UnknownInputParams } | { pathname: `/`; params?: Router.UnknownInputParams; } | { pathname: `/register`; params?: Router.UnknownInputParams; } | { pathname: `/login`; params?: Router.UnknownInputParams; } | { pathname: `/contacts`; params?: Router.UnknownInputParams; } | { pathname: `/stores/CourierOrderCard`; params?: Router.UnknownInputParams; } | { pathname: `/_sitemap`; params?: Router.UnknownInputParams; } | { pathname: `${'/(protected)'}` | `/`; params?: Router.UnknownInputParams; } | { pathname: `${'/(protected)'}/orders` | `/orders`; params?: Router.UnknownInputParams; } | { pathname: `${'/(protected)'}/payments` | `/payments`; params?: Router.UnknownInputParams; } | { pathname: `${'/(protected)'}/profile` | `/profile`; params?: Router.UnknownInputParams; } | { pathname: `${'/(public)'}/contacts` | `/contacts`; params?: Router.UnknownInputParams; } | { pathname: `${'/(public)'}/forgot-password` | `/forgot-password`; params?: Router.UnknownInputParams; } | { pathname: `${'/(public)'}/login` | `/login`; params?: Router.UnknownInputParams; } | { pathname: `${'/(public)'}/register` | `/register`; params?: Router.UnknownInputParams; } | { pathname: `/stores/HomeScreen`; params?: Router.UnknownInputParams; };
      hrefOutputParams: { pathname: Router.RelativePathString, params?: Router.UnknownOutputParams } | { pathname: Router.ExternalPathString, params?: Router.UnknownOutputParams } | { pathname: `/`; params?: Router.UnknownOutputParams; } | { pathname: `/register`; params?: Router.UnknownOutputParams; } | { pathname: `/login`; params?: Router.UnknownOutputParams; } | { pathname: `/contacts`; params?: Router.UnknownOutputParams; } | { pathname: `/stores/CourierOrderCard`; params?: Router.UnknownOutputParams; } | { pathname: `/_sitemap`; params?: Router.UnknownOutputParams; } | { pathname: `${'/(protected)'}` | `/`; params?: Router.UnknownOutputParams; } | { pathname: `${'/(protected)'}/orders` | `/orders`; params?: Router.UnknownOutputParams; } | { pathname: `${'/(protected)'}/payments` | `/payments`; params?: Router.UnknownOutputParams; } | { pathname: `${'/(protected)'}/profile` | `/profile`; params?: Router.UnknownOutputParams; } | { pathname: `${'/(public)'}/contacts` | `/contacts`; params?: Router.UnknownOutputParams; } | { pathname: `${'/(public)'}/forgot-password` | `/forgot-password`; params?: Router.UnknownOutputParams; } | { pathname: `${'/(public)'}/login` | `/login`; params?: Router.UnknownOutputParams; } | { pathname: `${'/(public)'}/register` | `/register`; params?: Router.UnknownOutputParams; } | { pathname: `/stores/HomeScreen`; params?: Router.UnknownOutputParams; };
      href: Router.RelativePathString | Router.ExternalPathString | `/${`?${string}` | `#${string}` | ''}` | `/register${`?${string}` | `#${string}` | ''}` | `/login${`?${string}` | `#${string}` | ''}` | `/contacts${`?${string}` | `#${string}` | ''}` | `/stores/CourierOrderCard${`?${string}` | `#${string}` | ''}` | `/_sitemap${`?${string}` | `#${string}` | ''}` | `${'/(protected)'}${`?${string}` | `#${string}` | ''}` | `/${`?${string}` | `#${string}` | ''}` | `${'/(protected)'}/orders${`?${string}` | `#${string}` | ''}` | `/orders${`?${string}` | `#${string}` | ''}` | `${'/(protected)'}/payments${`?${string}` | `#${string}` | ''}` | `/payments${`?${string}` | `#${string}` | ''}` | `${'/(protected)'}/profile${`?${string}` | `#${string}` | ''}` | `/profile${`?${string}` | `#${string}` | ''}` | `${'/(public)'}/contacts${`?${string}` | `#${string}` | ''}` | `/contacts${`?${string}` | `#${string}` | ''}` | `${'/(public)'}/forgot-password${`?${string}` | `#${string}` | ''}` | `/forgot-password${`?${string}` | `#${string}` | ''}` | `${'/(public)'}/login${`?${string}` | `#${string}` | ''}` | `/login${`?${string}` | `#${string}` | ''}` | `${'/(public)'}/register${`?${string}` | `#${string}` | ''}` | `/register${`?${string}` | `#${string}` | ''}` | `/stores/HomeScreen${`?${string}` | `#${string}` | ''}` | { pathname: Router.RelativePathString, params?: Router.UnknownInputParams } | { pathname: Router.ExternalPathString, params?: Router.UnknownInputParams } | { pathname: `/`; params?: Router.UnknownInputParams; } | { pathname: `/register`; params?: Router.UnknownInputParams; } | { pathname: `/login`; params?: Router.UnknownInputParams; } | { pathname: `/contacts`; params?: Router.UnknownInputParams; } | { pathname: `/stores/CourierOrderCard`; params?: Router.UnknownInputParams; } | { pathname: `/_sitemap`; params?: Router.UnknownInputParams; } | { pathname: `${'/(protected)'}` | `/`; params?: Router.UnknownInputParams; } | { pathname: `${'/(protected)'}/orders` | `/orders`; params?: Router.UnknownInputParams; } | { pathname: `${'/(protected)'}/payments` | `/payments`; params?: Router.UnknownInputParams; } | { pathname: `${'/(protected)'}/profile` | `/profile`; params?: Router.UnknownInputParams; } | { pathname: `${'/(public)'}/contacts` | `/contacts`; params?: Router.UnknownInputParams; } | { pathname: `${'/(public)'}/forgot-password` | `/forgot-password`; params?: Router.UnknownInputParams; } | { pathname: `${'/(public)'}/login` | `/login`; params?: Router.UnknownInputParams; } | { pathname: `${'/(public)'}/register` | `/register`; params?: Router.UnknownInputParams; } | { pathname: `/stores/HomeScreen`; params?: Router.UnknownInputParams; };
    }
  }
}
